page_gen-dirs: true # uncomment, if you prefer to generate named folders
plugins:
  - jekyll-datapage-generator

page_gen:
  - data: 'sample_comma_separated_TBESH_formatted'
    template: 'lexiconEntry'
    dir: 'w'
    index_files: false
    name_expr: record["strongNumber"].to_i.to_s
#    name: 'strongNumber'    
